name: test my action
on: [push]
jobs:
  testing_action:
    runs-on: ubuntu-latest
    steps:
    - name: test action
      uses: abelhatembentayeb/hatem_first_actions@master
      with:
        devops: "dev and ops conbination hhhh"
        